### ISSUE TITLE
Preprocessor doesn't carry #defines into included files

### ISSUE THREAD

**Issue by jansel** [petabricks/petabricks#1]
In the following example, TEST should be replaced by foo:

```
~/petabricks/examples$ cat a.pbcc 
#define TEST foo
#include "b.pbcc"

~/petabricks/examples$ cat b.pbcc 
function TEST
to X
{}

~/petabricks/examples$ ../scripts/preprocessor.py a.pbcc 
#2 "b.pbcc"
transform TEST 
to _X 
{ to (_X X) from () { } } 
kleptocracy:~/petabricks/examples$ 
```

This is causing a major performance regression in the sort benchmark.

**Comment by mangpo** [comment]
I'll fix it tomorrow!

On Thu, Oct 13, 2011 at 1:42 AM, Jason Ansel <
reply@reply.github.com>wrote:

> In the following example, TEST should be replaced by foo:
> 
> ```
> ~/petabricks/examples$ cat a.pbcc
> #define TEST foo
> #include "b.pbcc"
> 
> ~/petabricks/examples$ cat b.pbcc
> function TEST
> to X
> {}
> 
> ~/petabricks/examples$ ../scripts/preprocessor.py a.pbcc
> # 2 "b.pbcc"
> transform TEST
> to _X
> { to (_X X) from () { } }
> kleptocracy:~/petabricks/examples$
> ```
> 
> This is causing a major performance regression in the sort benchmark.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/petabricks/petabricks/issues/1

## 

Mangpo
Phitchaya Phothilimthana
MIT Class of 2012
